version: '3.8'

services:
  backend:
    build: .
    container_name: photoshoot-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=0
    restart: always
    # We remove the volumes section for production to use the code inside the image
    # volumes:
    #   - .:/app
    command: gunicorn --worker-class sync --workers 2 --timeout 300 -b 0.0.0.0:5000 app:app
